update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,23 +10,14 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Step 1: Set up SSH agent with private key
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.1
         with:
           ssh-private-key: ${{ secrets.DEPLOY_KEY }}
-
-      # Step 2: Add GitHub to known hosts
-      - name: Push to server
-        uses: appleboy/ssh-action@master
-        with:
-          host: 157.173.205.31
-          username: root
-          key: ${{ secrets.DEPLOY_KEY }}
-          script: |
-            cd /var/www/store-web
-            git pull origin main
-
 
       # Step 3: Deploy to VPS
       - name: Deploy to VPS
@@ -43,10 +34,10 @@ jobs:
             set -e
             echo "Logged into VPS at $HOST"
 
-            # cd /var/www/store-web
-            # ssh -T git@github.com || echo "Failed to connect to GitHub via SSH"
-            # echo "Pulling latest code from GitHub"
-            # git pull origin main
+            cd /var/www/store-web
+            ssh -T git@github.com || echo "Failed to connect to GitHub via SSH"
+            echo "Pulling latest code from GitHub"
+            git pull origin main
 
             # Stop and remove the existing Docker container
             if [ \$(docker ps -q -f name=store-web) ]; then
